services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins # Dockerfile específico para Jenkins
    container_name: jenkins
    ports:
      - "8085:8081" # Cambiado el puerto interno de Jenkins a 8081
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=8081 # Cambiado al puerto interno 8081
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile.app # Dockerfile específico para la aplicación
    ports:
      - "8090:8080" # Cambiado de 8080 a 8090
    volumes:
      - ./logs:/app/logs # Volumen para logs si es necesario
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ecommjava?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306" # Cambiado de 3306 a 3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommjava
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
  jenkins_home:
  logs:
